### ISSUE TITLE
NTR for quantities that are measure "per cell" of a species or organism

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S02#3]
Relates to: https://github.com/nvs-vocabs/P01/issues/194

**Comment by gwemon** [comment]
Proposed definition: "The measured phenomenon is reported on a "per cell" basis."

**Comment by jakjonbodc** [comment]
Created S02 term 'per cell of' - S02038 
http://vocab.nerc.ac.uk/collection/S02/current/S02038/
